// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tagger$0 from "./pkg/tagger/models.js";

export function AddTag(tagName: string): $CancellablePromise<tagger$0.Tag | null> {
    return $Call.ByID(2772039574, tagName).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(1995139705);
}

export function GetAllFiles(): $CancellablePromise<tagger$0.File[]> {
    return $Call.ByID(3288142011).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetAllTags(): $CancellablePromise<tagger$0.TagMap> {
    return $Call.ByID(3835784709).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetDir(): $CancellablePromise<string> {
    return $Call.ByID(1427003228);
}

export function GetFile(fileId: number): $CancellablePromise<tagger$0.File | null> {
    return $Call.ByID(146432811, fileId).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Get the path to a file in Tagger's directory.
 * Does not verify that the file exists on disk, but only construts the path where the file is expected to be.
 */
export function GetFilepath(file: tagger$0.File | null): $CancellablePromise<string> {
    return $Call.ByID(704505468, file);
}

export function GetFilesByTag(tags: tagger$0.Tag[]): $CancellablePromise<tagger$0.File[]> {
    return $Call.ByID(2220106995, tags).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetTagById(id: number): $CancellablePromise<tagger$0.Tag | null> {
    return $Call.ByID(68444139, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetTagByName(name: string): $CancellablePromise<tagger$0.Tag | null> {
    return $Call.ByID(3006808501, name).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Get all files without any tags
 */
export function GetUntaggedFiles(): $CancellablePromise<tagger$0.File[]> {
    return $Call.ByID(664032793).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Import a file into Tagger, copying it from the source directory and adding it to the database.
 */
export function ImportFile(path: string): $CancellablePromise<tagger$0.File | null> {
    return $Call.ByID(3945022492, path).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ImportFilesDialog(): $CancellablePromise<void> {
    return $Call.ByID(877541761);
}

export function Open(): $CancellablePromise<void> {
    return $Call.ByID(1396752623);
}

export function OpenFile(file: tagger$0.File): $CancellablePromise<void> {
    return $Call.ByID(4175724449, file);
}

/**
 * Remove a file from the database and disk
 * If the file is not found on disk, assume that it was deleted and proceed normally
 */
export function RemoveFile(file: tagger$0.File | null): $CancellablePromise<void> {
    return $Call.ByID(29733185, file);
}

export function RemoveTag(tag: tagger$0.Tag | null): $CancellablePromise<void> {
    return $Call.ByID(2924440901, tag);
}

export function Reveal(file: tagger$0.File): $CancellablePromise<void> {
    return $Call.ByID(3136939158, file);
}

/**
 * Add a tag to a file.
 */
export function TagFile(file: tagger$0.File | null, tag: tagger$0.Tag | null): $CancellablePromise<void> {
    return $Call.ByID(1993529575, file, tag);
}

/**
 * Remove a specific tag from a file. Will not produce an error if either value is invalid.
 */
export function UntagFile(file: tagger$0.File | null, tag: tagger$0.Tag | null): $CancellablePromise<void> {
    return $Call.ByID(852450234, file, tag);
}

export function UpdateTag(tag: tagger$0.Tag | null): $CancellablePromise<void> {
    return $Call.ByID(1483561978, tag);
}

// Private type creation functions
const $$createType0 = tagger$0.Tag.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = tagger$0.File.createFrom;
const $$createType3 = $Create.Array($$createType2);
var $$createType4 = (function $$initCreateType4(...args: any[]): any {
    if ($$createType4 === $$initCreateType4) {
        $$createType4 = $$createType5;
    }
    return $$createType4(...args);
});
const $$createType5 = $Create.Map($Create.Any, $$createType0);
const $$createType6 = $Create.Nullable($$createType2);
