// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tagger$0 from "./pkg/tagger/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../wailsapp/wails/v3/pkg/application/models.js";

/**
 * @param {string} tagName
 * @returns {Promise<tagger$0.Tag | null> & { cancel(): void }}
 */
export function AddTag(tagName) {
    let $resultPromise = /** @type {any} */($Call.ByID(2772039574, tagName));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Close() {
    let $resultPromise = /** @type {any} */($Call.ByID(1995139705));
    return $resultPromise;
}

/**
 * @returns {Promise<tagger$0.File[]> & { cancel(): void }}
 */
export function GetAllFiles() {
    let $resultPromise = /** @type {any} */($Call.ByID(3288142011));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<tagger$0.Tag[]> & { cancel(): void }}
 */
export function GetAllTags() {
    let $resultPromise = /** @type {any} */($Call.ByID(3835784709));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType4($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {number} id
 * @returns {Promise<tagger$0.File | null> & { cancel(): void }}
 */
export function GetFile(id) {
    let $resultPromise = /** @type {any} */($Call.ByID(146432811, id));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType5($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {tagger$0.File} file
 * @returns {Promise<string> & { cancel(): void }}
 */
export function GetFilepath(file) {
    let $resultPromise = /** @type {any} */($Call.ByID(704505468, file));
    return $resultPromise;
}

/**
 * @param {tagger$0.Tag[]} tags
 * @returns {Promise<tagger$0.File[]> & { cancel(): void }}
 */
export function GetFiles(tags) {
    let $resultPromise = /** @type {any} */($Call.ByID(359293832, tags));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * TODO do this with a recursive CTE in the database, not like this
 * @param {tagger$0.Tag} tag
 * @returns {Promise<tagger$0.Tag[]> & { cancel(): void }}
 */
export function GetParentTags(tag) {
    let $resultPromise = /** @type {any} */($Call.ByID(923233200, tag));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType4($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {string} name
 * @returns {Promise<tagger$0.Tag | null> & { cancel(): void }}
 */
export function GetTag(name) {
    let $resultPromise = /** @type {any} */($Call.ByID(535759851, name));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType1($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @returns {Promise<tagger$0.File[]> & { cancel(): void }}
 */
export function GetUntaggedFiles() {
    let $resultPromise = /** @type {any} */($Call.ByID(664032793));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType3($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {string} path
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ImportFile(path) {
    let $resultPromise = /** @type {any} */($Call.ByID(3945022492, path));
    return $resultPromise;
}

/**
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ImportFilesDialog() {
    let $resultPromise = /** @type {any} */($Call.ByID(877541761));
    return $resultPromise;
}

/**
 * @param {string} path
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Open(path) {
    let $resultPromise = /** @type {any} */($Call.ByID(1396752623, path));
    return $resultPromise;
}

/**
 * @returns {Promise<string> & { cancel(): void }}
 */
export function OpenDBDialog() {
    let $resultPromise = /** @type {any} */($Call.ByID(30352029));
    return $resultPromise;
}

/**
 * @param {tagger$0.File} file
 * @returns {Promise<void> & { cancel(): void }}
 */
export function OpenFile(file) {
    let $resultPromise = /** @type {any} */($Call.ByID(4175724449, file));
    return $resultPromise;
}

/**
 * Remove a file from the database and disk
 * If the file is not found on disk, assume that it was deleted and proceed normally
 * @param {tagger$0.File} file
 * @returns {Promise<void> & { cancel(): void }}
 */
export function RemoveFile(file) {
    let $resultPromise = /** @type {any} */($Call.ByID(29733185, file));
    return $resultPromise;
}

/**
 * @param {tagger$0.Tag} tag
 * @returns {Promise<void> & { cancel(): void }}
 */
export function RemoveTag(tag) {
    let $resultPromise = /** @type {any} */($Call.ByID(2924440901, tag));
    return $resultPromise;
}

/**
 * @param {tagger$0.File} file
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Reveal(file) {
    let $resultPromise = /** @type {any} */($Call.ByID(3136939158, file));
    return $resultPromise;
}

/**
 * @param {application$0.ServiceOptions} options
 * @returns {Promise<void> & { cancel(): void }}
 */
export function ServiceStartup(options) {
    let $resultPromise = /** @type {any} */($Call.ByID(25898875, options));
    return $resultPromise;
}

/**
 * @param {tagger$0.File} file
 * @param {tagger$0.Tag} tag
 * @returns {Promise<void> & { cancel(): void }}
 */
export function TagFile(file, tag) {
    let $resultPromise = /** @type {any} */($Call.ByID(1993529575, file, tag));
    return $resultPromise;
}

/**
 * @param {tagger$0.File} file
 * @param {tagger$0.Tag} tag
 * @returns {Promise<void> & { cancel(): void }}
 */
export function UntagFile(file, tag) {
    let $resultPromise = /** @type {any} */($Call.ByID(852450234, file, tag));
    return $resultPromise;
}

/**
 * @param {tagger$0.Tag} tag
 * @returns {Promise<void> & { cancel(): void }}
 */
export function UpdateTag(tag) {
    let $resultPromise = /** @type {any} */($Call.ByID(1483561978, tag));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = tagger$0.Tag.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = tagger$0.File.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $Create.Nullable($$createType2);
