// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class File {
    /**
     * Creates a new File instance.
     * @param {Partial<File>} [$$source = {}] - The source object to create the File.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * File
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("filetype" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filetype"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * FileTags
             * @member
             * @type {Tag[]}
             */
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new File instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {File}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        return new File(/** @type {Partial<File>} */($$parsedSource));
    }
}

export class Tag {
    /**
     * Creates a new Tag instance.
     * @param {Partial<Tag>} [$$source = {}] - The source object to create the Tag.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parents" in $$source)) {
            /**
             * @member
             * @type {Tag[]}
             */
            this["parents"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Tag}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parents" in $$parsedSource) {
            $$parsedSource["parents"] = $$createField2_0($$parsedSource["parents"]);
        }
        return new Tag(/** @type {Partial<Tag>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Tag.createFrom;
const $$createType1 = $Create.Array($$createType0);
