// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class File {
    /**
     * File
     */
    "id": number;
    "hash": string;
    "filetype": string;
    "description": string;

    /**
     * FileTags
     */
    "tags": Tag[];

    /** Creates a new File instance. */
    constructor($$source: Partial<File> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("hash" in $$source)) {
            this["hash"] = "";
        }
        if (!("filetype" in $$source)) {
            this["filetype"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new File instance from a string or object.
     */
    static createFrom($$source: any = {}): File {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new File($$parsedSource as Partial<File>);
    }
}

export class Tag {
    "id": number;
    "name": string;
    "parents": number[];

    /** Creates a new Tag instance. */
    constructor($$source: Partial<Tag> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("parents" in $$source)) {
            this["parents"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     */
    static createFrom($$source: any = {}): Tag {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("parents" in $$parsedSource) {
            $$parsedSource["parents"] = $$createField2_0($$parsedSource["parents"]);
        }
        return new Tag($$parsedSource as Partial<Tag>);
    }
}

export type TagMap = { [_: `${number}`]: Tag };

// Private type creation functions
const $$createType0 = Tag.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
