FROM mcr.microsoft.com/devcontainers/go:1-1.23-bookworm

# Wails dependencies
RUN apt update && apt install -y nodejs npm libgtk-3-dev libwebkit2gtk-4.1-dev nsis

# install wails
RUN go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest

# Tagger dependencies
RUN apt install -y libfuse-dev

# dev nice-to-haves
RUN apt install -y sqlitebrowser feh mpv