FROM mcr.microsoft.com/devcontainers/go:1-1.23-bookworm

RUN apt update && apt install -y nodejs npm libgtk-3-dev libwebkit2gtk-4.1-dev nsis

RUN go install -v github.com/wailsapp/wails/v3/cmd/wails3@latest

RUN apt install -y libfuse-dev