// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile(arg1) {
  return window['go']['main']['TaggerApp']['AddFile'](arg1);
}

export function AddTag(arg1) {
  return window['go']['main']['TaggerApp']['AddTag'](arg1);
}

export function GetAllFiles() {
  return window['go']['main']['TaggerApp']['GetAllFiles']();
}

export function GetAllTags() {
  return window['go']['main']['TaggerApp']['GetAllTags']();
}

export function GetFile(arg1) {
  return window['go']['main']['TaggerApp']['GetFile'](arg1);
}

export function GetFiles(arg1) {
  return window['go']['main']['TaggerApp']['GetFiles'](arg1);
}

export function GetTag(arg1) {
  return window['go']['main']['TaggerApp']['GetTag'](arg1);
}

export function GetUntaggedFiles() {
  return window['go']['main']['TaggerApp']['GetUntaggedFiles']();
}

export function ImportFile(arg1) {
  return window['go']['main']['TaggerApp']['ImportFile'](arg1);
}

export function ImportFilesDialog() {
  return window['go']['main']['TaggerApp']['ImportFilesDialog']();
}

export function Open(arg1) {
  return window['go']['main']['TaggerApp']['Open'](arg1);
}

export function OpenDBDialog() {
  return window['go']['main']['TaggerApp']['OpenDBDialog']();
}

export function OpenFile(arg1) {
  return window['go']['main']['TaggerApp']['OpenFile'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['TaggerApp']['ReadFile'](arg1);
}

export function RemoveFile(arg1) {
  return window['go']['main']['TaggerApp']['RemoveFile'](arg1);
}

export function RemoveTag(arg1) {
  return window['go']['main']['TaggerApp']['RemoveTag'](arg1);
}

export function TagFile(arg1, arg2) {
  return window['go']['main']['TaggerApp']['TagFile'](arg1, arg2);
}

export function UntagFile(arg1, arg2) {
  return window['go']['main']['TaggerApp']['UntagFile'](arg1, arg2);
}
