// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFile(arg1:main.File):Promise<void>;

export function AddTag(arg1:string):Promise<main.Tag>;

export function GetAllFiles():Promise<Array<main.File>>;

export function GetAllTags():Promise<Array<main.Tag>>;

export function GetFile(arg1:string):Promise<main.File>;

export function GetFiles(arg1:Array<main.Tag>):Promise<Array<main.File>>;

export function GetTag(arg1:string):Promise<main.Tag>;

export function GetUntaggedFiles():Promise<Array<main.File>>;

export function ImportFile(arg1:string):Promise<void>;

export function ImportFilesDialog():Promise<void>;

export function Open(arg1:string):Promise<void>;

export function OpenDBDialog():Promise<string>;

export function OpenFile(arg1:main.File):Promise<void>;

export function ReadFile(arg1:main.File):Promise<main.File>;

export function RemoveFile(arg1:main.File):Promise<void>;

export function RemoveTag(arg1:main.Tag):Promise<void>;

export function TagFile(arg1:main.File,arg2:main.Tag):Promise<void>;

export function UntagFile(arg1:main.File,arg2:main.Tag):Promise<void>;
